---
title: "genetic_correlations"
author: "<h3>Author</h3>Brian M. Schilder"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document: 
    theme: spacelab
    highlight: zenburn 
    code_folding: show 
    toc: true 
    toc_float: true
    smooth_scroll: true
    number_sections: false 
    self_contained: true 
---

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = here::here())

library(dplyr)
library(ggplot2)
set.seed(2019)
```


# [Bryois 2020](https://www.nature.com/articles/s41588-020-0610-9)

```{r}
bryois <- readxl::read_excel(here::here("data/metaanalysis/TableS2.xlsx"), sheet="Bryois2020_corr")

mat_bryois <- as.matrix(bryois$rg) %>% `rownames<-`(bryois$Trait2) %>% `colnames<-`("rg")

heat <- ggplot(bryois, aes(y=Trait2, x=1, fill=rg)) +
  geom_tile() + 
  theme_bw()
plotly::ggplotly(heat)
```



# LD Hub 

I began to explore this dataset but then realized it does not contain any Parkinson's Disease GWAS.

```{r, eval=FALSE}
rg = xlsx::read.xlsx(here::here("data/LD_Hub/LD-Hub_genetic_correlation_221x221_no_ENIGMA.xlsx"), sheetName = "rG") %>% 
  tibble::column_to_rownames("NA.")
colnames(rg) <- gsub("[.]","-",colnames(rg))
row.names(rg) <- gsub("[.]","-",row.names(rg))
rg[rg=="/"] <- NA 
rg <- Matrix::as.matrix(rg, sparse = T)


rp = xlsx::read.xlsx(here::here("data/LD-Hub_genetic_correlation_221x221_no_ENIGMA.xlsx"), sheetName = "rP")%>%
    tibble::column_to_rownames("NA.")
colnames(rp) <- gsub("[.]","-",colnames(rp))
row.names(rp) <- gsub("[.]","-",row.names(rp))
rp[rp=="/"] <- NA 
rp <- Matrix::as.matrix(rp, sparse = T)

```

Check for Parkinson's

```{r, eval=FALSE}
grep("Parkinson",colnames(rp), ignore.case = T, value = T)
```


# Session Info

<details> 

```{r}
utils::sessionInfo()
```

</details>

